server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobms_db
    username: postgres
    password: "*Mareen7#"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

